name: CI

on:
  push:
    branches: [ main, master ]  # Added master as some repos use this
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, reopened]  # Specific PR events

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
      REACT_APP_SUPABASE_ANON_KEY: ${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm test